baseURL: https://nito95.github.io/
title: nito95 blog
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    title: nito95
    description: "nito95 blog"
    keywords: [Blog, Portfolio]
    defaultTheme: light
    disableThemeToggle: false
    enableInlineShortcodes: true

    ShowReadingTime: false
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    custom_css: ["/css/custom.css"]

    assets:
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    profileMode:
        enabled: false

    homeInfoParams:
        Title: Naoya Ito
        Content: >
            - 東京都内でソフトウェアエンジニアをしています。

            - 詳細はこちら → [About Me](/about/)

    socialIcons:
        - name: facebook
          url: "https://m.me/naoya.ito.1829/"
        - name: github
          url: "https://github.com/nito95/"
        - name: linkedin
          url: "https://www.linkedin.com/in/naoya-ito-68728a116/"

    analytics:
        google:
            SiteVerificationTag: "G-FT3WYS86E7"

    cover:
        hidden: true
        hiddenInList: true
        hiddenInSingle: true

menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 10
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
